import { CommonModule } from '@angular/common';
import { ChangeDetectorRef, Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';
import { firstValueFrom } from 'rxjs';
import { ButtonModule } from 'primeng/button';
import { CardModule } from 'primeng/card';
import { ConfirmDialogModule } from 'primeng/confirmdialog';
import { ConfirmationService, MessageService } from 'primeng/api';
import { DatePickerModule } from 'primeng/datepicker';
import { DialogModule } from 'primeng/dialog';
import { InputNumberModule } from 'primeng/inputnumber';
import { MessageModule } from 'primeng/message';
import { SelectModule } from 'primeng/select';
import { SkeletonModule } from 'primeng/skeleton';
import { TableModule } from 'primeng/table';
import { TabsModule } from 'primeng/tabs';
import { TagModule } from 'primeng/tag';
import { ToastModule } from 'primeng/toast';
import { PrimeNG } from 'primeng/config';
import { VacacionesService, VacacionesSaldo, VacacionesSolicitud, EstadoVacaciones, VacacionesCalendarioDia } from '../services/vacaciones.service';

@Component({ selector: 'app-mis-vacaciones', standalone: true, imports: [CommonModule, FormsModule, RouterModule, ButtonModule, CardModule, ConfirmDialogModule, DatePickerModule, DialogModule, InputNumberModule, MessageModule, SelectModule, SkeletonModule, TableModule, TabsModule, TagModule, ToastModule], providers: [MessageService, ConfirmationService], templateUrl: './misVacaciones.html', styleUrl: './misVacaciones.css' })
export class MisVacaciones implements OnInit {
  documento = ''; usuario = ''; saldos: VacacionesSaldo[] = []; solicitudes: VacacionesSolicitud[] = []; calendario: VacacionesCalendarioDia[] = [];
  cargando = false; guardando = false; detalleVisible = false; nuevaVisible = false; solicitudSeleccionada: VacacionesSolicitud | null = null;
  fechaCalendario: Date = new Date(); rangoCalendario: Date[] | null = null; fechasSeleccionadasCalendario: Date[] = []; fechasOcupadasCalendario = new Map<string, EstadoVacaciones>();
  estadoFiltro = ''; periodoFiltro: number | string | null = null; fechaDesde: Date | null = null; fechaHasta: Date | null = null; tab = '0';
  periodoNuevo: number | string | null = null; fechaInicio: Date | null = null; cantidadDias = 1; observacion = '';
  fechasPreview: Date[] = []; mensajeError = '';
  readonly estados = ['', 'BORRADOR', 'PENDIENTE', 'APROBADA', 'RECHAZADA', 'CANCELADA'];
  readonly estadosOpciones = [{ label: 'Todos los estados', value: '' }, ...this.estados.slice(1).map(value => ({ label: value, value }))];
  readonly localeEspanol = { firstDayOfWeek: 1, dayNames: ['domingo', 'lunes', 'martes', 'miércoles', 'jueves', 'viernes', 'sábado'], dayNamesShort: ['dom', 'lun', 'mar', 'mié', 'jue', 'vie', 'sáb'], dayNamesMin: ['D', 'L', 'M', 'X', 'J', 'V', 'S'], monthNames: ['enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio', 'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'], monthNamesShort: ['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sep', 'oct', 'nov', 'dic'], today: 'Hoy', clear: 'Limpiar' };
  constructor(private vacaciones: VacacionesService, private messages: MessageService, private confirm: ConfirmationService, private cdr: ChangeDetectorRef, private primeng: PrimeNG) {}
  ngOnInit(): void { this.primeng.setTranslation(this.localeEspanol); this.documento = this.cookie('usuario'); this.usuario = this.documento; this.cargar(); }
  cargar(): void { if (!this.documento) return; this.cargando = true; this.mensajeError = ''; Promise.all([firstValueFrom(this.vacaciones.obtenerSaldos(this.documento)), firstValueFrom(this.vacaciones.listarSolicitudes({ nroDocumento: this.documento, estado: this.estadoFiltro, fechaDesde: this.iso(this.fechaDesde), fechaHasta: this.iso(this.fechaHasta) }))]).then(([saldos, solicitudes]) => { this.saldos = saldos.map(saldo => ({ ...saldo, periodo: this.formatearPeriodo(saldo) })); this.solicitudes = solicitudes; this.actualizarFechasOcupadas(); this.periodoNuevo ??= saldos[0]?.idPeriodo ?? null; this.cargando = false; this.cargarCalendario(); this.cdr.detectChanges(); }).catch(e => { this.mensajeError = e?.error?.message || 'No se pudo cargar la información de vacaciones.'; this.cargando = false; this.cdr.detectChanges(); }); }
  buscar(): void { this.cargar(); }
  limpiar(): void { this.estadoFiltro = ''; this.periodoFiltro = null; this.fechaDesde = null; this.fechaHasta = null; this.cargar(); }
  abrirNueva(fecha?: Date): void { this.solicitudSeleccionada = null; this.fechaInicio = fecha ?? null; this.cantidadDias = 1; this.observacion = ''; this.periodoNuevo ??= this.saldos[0]?.idPeriodo ?? null; this.actualizarPreview(); this.nuevaVisible = true; }
  seleccionarRangoCalendario(rango: Date[] | null): void { this.rangoCalendario = rango; if (!rango || rango.length < 2) return; const ordenadas = [...rango].sort((a, b) => a.getTime() - b.getTime()); const inicio = ordenadas[0]; const fin = ordenadas[ordenadas.length - 1]; this.solicitudSeleccionada = null; this.fechaInicio = inicio; this.fechasPreview = this.generarRangoCompleto(inicio, fin); this.cantidadDias = this.fechasPreview.length; this.observacion = ''; this.periodoNuevo ??= this.saldos[0]?.idPeriodo ?? null; this.nuevaVisible = true; }
  editar(item: VacacionesSolicitud): void { if (!this.esBorrador(item)) return; this.solicitudSeleccionada = item; this.periodoNuevo = item.idPeriodo ?? this.saldos.find(s => s.periodo === item.periodo)?.idPeriodo ?? null; this.fechaInicio = this.parse(item.fechaInicio); this.observacion = item.observacion || ''; this.cantidadDias = item.diasSolicitados ?? item.dias ?? 1; this.actualizarPreview(); this.nuevaVisible = true; }
  actualizarPreview(): void { this.fechasPreview = []; if (!this.fechaInicio || this.cantidadDias < 1) return; const date = new Date(this.fechaInicio); let guardados = 0; for (let i = 0; i < 370 && guardados < this.cantidadDias; i++) { const actual = new Date(date); actual.setDate(date.getDate() + i); if (actual.getDay() === 0) continue; this.fechasPreview.push(actual); guardados++; } }
  guardar(enviar = false): void { const saldo = this.saldos.find(s => String(s.idPeriodo) === String(this.periodoNuevo)); if (!this.fechaInicio || this.periodoNuevo === null || this.periodoNuevo === undefined || !saldo || this.fechasPreview.length === 0) { this.messages.add({ severity: 'warn', summary: 'Datos incompletos', detail: 'Selecciona periodo, fecha y cantidad de días.' }); return; } if (this.fechasPreview.length > Number(saldo.diasDisponibles)) { this.messages.add({ severity: 'warn', summary: 'Saldo insuficiente', detail: 'La cantidad supera los días disponibles.' }); return; } const request: any = { nroDocumento: this.documento, idPeriodo: this.normalizarId(this.periodoNuevo), fechaInicio: this.isoDateTime(this.fechasPreview[0]), fechaFin: this.isoDateTime(this.fechasPreview[this.fechasPreview.length - 1]), usuario: this.usuario, observacion: this.observacion }; if (this.solicitudSeleccionada) { request.idSolicitud = this.normalizarId(this.solicitudSeleccionada.idSolicitud); request.versionOriginal = this.solicitudSeleccionada.versionOriginal === undefined || this.solicitudSeleccionada.versionOriginal === null ? '' : String(this.solicitudSeleccionada.versionOriginal); } this.guardando = true; this.vacaciones.guardarSolicitud(request).subscribe({ next: response => { const id = response?.data?.idSolicitud ?? response?.data?.id ?? response?.idSolicitud ?? response?.id ?? this.solicitudSeleccionada?.idSolicitud; if (enviar && id !== null && id !== undefined) this.enviar(id); else { this.guardando = false; this.nuevaVisible = false; this.messages.add({ severity: 'success', summary: 'Solicitud guardada', detail: 'Se guardó como borrador.' }); this.cargar(); } }, error: e => { this.guardando = false; this.messages.add({ severity: 'error', summary: 'Error al guardar', detail: e?.error?.message || e?.error?.title || 'El servicio rechazó la solicitud. Verifica las fechas y el periodo.' }); } }); }
  enviar(id: number | string, versionOriginal?: number | string): void { const version = versionOriginal ?? this.solicitudSeleccionada?.versionOriginal; this.vacaciones.enviarSolicitud(id, { usuarioAprobador: 'ADMINISTRADOR', usuario: this.usuario, fechaActual: new Date().toISOString(), versionOriginal: version == null ? '' : String(version) }).subscribe({ next: () => { this.guardando = false; this.nuevaVisible = false; this.messages.add({ severity: 'success', summary: 'Enviada', detail: 'Solicitud enviada a aprobación.' }); this.cargar(); }, error: e => { this.guardando = false; this.messages.add({ severity: 'error', summary: 'Error', detail: e?.error?.message || 'No se pudo enviar.' }); } }); }
  enviarSolicitud(item: VacacionesSolicitud): void { this.confirm.confirm({ message: '¿Enviar esta solicitud a aprobación?', header: 'Confirmar envío', icon: 'pi pi-send', accept: () => this.enviar(item.idSolicitud, item.version ?? item.versionOriginal) }); }
  cancelar(item: VacacionesSolicitud): void { this.confirm.confirm({ message: '¿Cancelar esta solicitud?', header: 'Confirmar cancelación', icon: 'pi pi-exclamation-triangle', accept: () => this.vacaciones.cancelarSolicitud(item.idSolicitud, { usuario: this.usuario, motivo: 'Cancelación solicitada por el usuario', fechaActual: new Date().toISOString(), versionOriginal: item.versionOriginal }).subscribe({ next: () => { this.messages.add({ severity: 'success', summary: 'Cancelada', detail: 'Solicitud cancelada.' }); this.cargar(); }, error: e => this.messages.add({ severity: 'error', summary: 'Error', detail: e?.error?.message || 'No se pudo cancelar.' }) }) }); }
  verDetalle(item: VacacionesSolicitud): void { this.solicitudSeleccionada = item; this.detalleVisible = true; this.vacaciones.obtenerSolicitud(item.idSolicitud).subscribe({ next: value => { const detalle: any = value ?? {}; const cabecera = detalle.solicitud ?? detalle; this.solicitudSeleccionada = { ...item, ...cabecera, diasDetalle: detalle.dias ?? detalle.diasDetalle ?? item.diasDetalle, aprobaciones: detalle.aprobaciones ?? item.aprobaciones, movimientos: detalle.movimientos ?? item.movimientos }; this.cdr.detectChanges(); }, error: e => this.messages.add({ severity: 'warn', summary: 'Detalle parcial', detail: e?.error?.message || 'Se muestran los datos disponibles de la solicitud.' }) }); }
  cargarCalendario(): void { const inicio = new Date(this.fechaCalendario.getFullYear(), this.fechaCalendario.getMonth(), 1); const fin = new Date(this.fechaCalendario.getFullYear(), this.fechaCalendario.getMonth() + 1, 0); this.vacaciones.obtenerCalendario(this.documento, this.iso(inicio), this.iso(fin)).subscribe({ next: value => { this.calendario = value?.dias ?? []; this.cdr.detectChanges(); }, error: () => { this.calendario = []; this.cdr.detectChanges(); } }); }
  severidad(estado?: string): 'secondary' | 'warn' | 'success' | 'danger' | 'contrast' { switch ((estado || '').toUpperCase()) { case 'PENDIENTE': return 'warn'; case 'APROBADA': return 'success'; case 'RECHAZADA': return 'danger'; case 'CANCELADA': return 'contrast'; default: return 'secondary'; } }
  esBorrador(item: VacacionesSolicitud): boolean { return String(item.estado).toUpperCase() === 'BORRADOR'; }
  puedeCancelar(item: VacacionesSolicitud): boolean { return ['BORRADOR', 'PENDIENTE', 'APROBADA'].includes(String(item.estado).toUpperCase()); }
  dias(item: VacacionesSolicitud): number { return item.diasSolicitados ?? item.dias ?? 0; }
  formatearPeriodo(item: VacacionesSaldo | VacacionesSolicitud): string { const actual = String(item.periodo ?? '').trim(); if (/^\d{4}\s*[-/]\s*\d{4}$/.test(actual)) return actual.replace('/', '-').replace(/\s+/g, ''); const inicio = String((item as VacacionesSaldo).fechaInicioPeriodo ?? '').substring(0, 4); const fin = String((item as VacacionesSaldo).fechaFinPeriodo ?? '').substring(0, 4); if (/^\d{4}$/.test(inicio) && /^\d{4}$/.test(fin)) return `${inicio}-${fin}`; const years = actual.match(/\d{4}/g); return years && years.length >= 2 ? `${years[0]}-${years[1]}` : actual || String(item.idPeriodo ?? '-'); }
  contarDiasIncluidos(inicio: Date, fin: Date): number { const desde = new Date(inicio.getFullYear(), inicio.getMonth(), inicio.getDate()); const hasta = new Date(fin.getFullYear(), fin.getMonth(), fin.getDate()); return Math.max(1, Math.floor((hasta.getTime() - desde.getTime()) / 86400000) + 1); }
  private generarRangoCompleto(inicio: Date, fin: Date): Date[] { const fechas: Date[] = []; const actual = new Date(inicio.getFullYear(), inicio.getMonth(), inicio.getDate()); const limite = new Date(fin.getFullYear(), fin.getMonth(), fin.getDate()); while (actual <= limite) { fechas.push(new Date(actual)); actual.setDate(actual.getDate() + 1); } return fechas; }
  esDiaMarcado(date: { day: number; month: number; year: number }): boolean { return this.fechasOcupadasCalendario.has(this.claveFecha(new Date(date.year, date.month, date.day))); }
  estadoDiaMarcado(date: { day: number; month: number; year: number }): string { return (this.fechasOcupadasCalendario.get(this.claveFecha(new Date(date.year, date.month, date.day))) || '').toLowerCase(); }
  private actualizarFechasOcupadas(): void { this.fechasOcupadasCalendario.clear(); for (const solicitud of this.solicitudes) { const inicio = this.parse(solicitud.fechaInicio); const fin = this.parse(solicitud.fechaFin) || inicio; if (!inicio || !fin) continue; for (let fecha = new Date(inicio); fecha <= fin; fecha.setDate(fecha.getDate() + 1)) this.fechasOcupadasCalendario.set(this.claveFecha(fecha), solicitud.estado); } }
  private claveFecha(fecha: Date): string { return `${fecha.getFullYear()}-${String(fecha.getMonth() + 1).padStart(2, '0')}-${String(fecha.getDate()).padStart(2, '0')}`; }
  private iso(value: Date | null): string { if (!value) return ''; return `${value.getFullYear()}-${String(value.getMonth() + 1).padStart(2, '0')}-${String(value.getDate()).padStart(2, '0')}`; }
  private isoDateTime(value: Date): string { return this.iso(value); }
  private normalizarId(value: number | string): number | string { const numeric = Number(value); return Number.isNaN(numeric) ? value : numeric; }
  private parse(value?: string): Date | null { if (!value) return null; const d = new Date(`${value.substring(0, 10)}T00:00:00`); return Number.isNaN(d.getTime()) ? null : d; }
  private cookie(name: string): string { const found = document.cookie.split('; ').find(c => c.startsWith(`${name}=`)); return found ? decodeURIComponent(found.split('=').slice(1).join('=')) : ''; }
}
